### PR TITLE
Improve accessibility of main navigation

### PR DESCRIPTION
**Pull request by wesruv**
I think this is still a WIP, but I'd like some review. Here's my thoughts on it here: https://www.dropbox.com/s/wlkza3ph2fpq96o/web2020-menu.MP4?dl=0

Increased horizontal hit area of navigation (padding on links to match vertical padding)
Made focus on navigation elements open them
Made sure focus on a new dropdown closed any open ones

### CODE REVIEW

**Comment by wesruv** [comment]
@clizzy12 I hear your the guy to take a look at this

**Comment by clizzy12** [comment]
Looks Good. I'll wait until you make that code change that involves the mark-up.

**Comment by wesruv** [comment]
Just stumbled across this: https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events

Very possible I need to emit an event from NavDrop to MainHeader instead of passing a function as a prop...

**Comment by clizzy12** [comment]
Hmm, from my testing, the mobile slide menu now isn't showing.

Also, I agree, I like to keep props only passing data, and not functionality. Emitting an event would be much better.

**Comment by wesruv** [comment]
Can't get the custom event to fire for the life of me :/

Probably missing something simple, but the function in `v-on` on the parent component isn't getting called :angry:

**Comment by clizzy12** [comment]
Not a problem, I'll merge this in and if we find problems or optimizations, we'll implement/fix them 👍

**Pull request merged**
